name: First React App With Github Actions - Workflow Demo
on: push
jobs:
  test:
    runs-on: ubuntu-latest # the server does not have our github repo code automatically ! we should get the code onto the server
    steps:
      - name: Get code
        uses: actions/checkout@v3 # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: Install NodeJS # This is optionnel because ubuntu-latest does not have NodeJS by default
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run React tests
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: Install NodeJS # This is optionnel because ubuntu-latest does not have NodeJS by default
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: echo "Deploying project ..."
